---
driver:
  name: docker
  dockerfile: test/platforms/Dockerfile
  cc_pattern: "<%= File.basename(Dir.pwd) %>"

provisioner:
  name: chef_solo
  attributes:
    cloudconductor:
      servers:
        ap_01:
          private_ip: '127.0.0.1'
          roles: 'ap'
          weight: '0'
      applications:
        jpetstore:
          type: 'dynamic'
          protocol: 'http'
          url: 'https://s3-ap-northeast-1.amazonaws.com/dev.cloudconductor.jp/sources/public/jpetstore.war'
          parameters:
            migration:
              type: 'sql'
              url: 'https://s3-ap-northeast-1.amazonaws.com/dev.cloudconductor.jp/sources/public/jpetstore_postgres.sql'

platforms:
  - name: centos-6.6
    driver:
      image: centos:centos6.6
      run_command: "/sbin/init"
  - name: centos-7
    driver:
      image: centos:centos7
      privileged: true
      run_command: "/sbin/init"

suites:
  - name: web_setup
    driver:
      cc_role: 'web'
    run_list:
      - role[web_setup]

  - name: web_configure
    driver:
      cc_role: 'web'
    run_list:
      - role[web_setup]
      - role[web_configure]

  - name: web_deploy
    driver:
      cc_role: 'web'
    run_list:
      - role[web_setup]
      - role[web_configure]
      - role[web_deploy]

  - name: ap_setup
    driver:
      cc_role: 'ap'
    run_list:
      - role[ap_setup]

  - name: ap_deploy
    driver:
      cc_role: 'ap'
    run_list:
      - role[ap_setup]
      - role[ap_deploy]

  - name: db_setup
    driver:
      cc_role: 'db'
    run_list:
      - role[db_setup]

  - name: db_configure
    driver:
      cc_role: 'db'
    run_list:
      - role[db_setup]
      - role[db_configure]

  - name: db_deploy
    driver:
      cc_role: 'db'
    run_list:
      - role[db_setup]
      - role[db_configure]
      - role[db_deploy]
