name             'backup_restore'
version          '0.0.1'
description      'Installs/Configures backups and run restore'
license          'Apache v2.0'
maintainer       'TIS Inc.'
maintainer_email 'ccndctr@gmail.com'

supports 'centos', '= 6.5'

depends 'backup'
depends 'cron'
depends 'percona'
depends 'yum-epel'
depends 's3cmd-master'
depends 's3cfg'
